Fix lines table overflow detection segfault
Zeex/samp-plugin-crashdetect pull request #101
Opened 2021-09-04 13:04 UTC by Cheaterman

2022-03-12 21:58 UTC, Zeex commented
Could you write a few lines to explain what this patch does? And where the values `33` and `0x10000` come from?

2022-03-14 12:42 UTC, Cheaterman commented
I think the title explains it pretty well. You're currently reading unmapped memory to find where the AMX ends, and (wrongly) expecting zeroes when you do (instead of garbage or an outright crash).

The values have to do with AMX structure. I honestly do not remember. This is tested, working, and most importantly _correct_ (at least more than the original code...).

2022-03-20 07:32 UTC, Zeex commented
OK, that's great, thanks

2022-10-10 10:03 UTC, Zeex requested changes
@Cheaterman Thanks for submitting this PR. Please check my comments if you still want to have this merged.

2022-10-10 10:03 UTC, Zeex commented on src/amx/amxdbg.c
> +  unsigned int biggest_possible_size = (
The source code of AMX is written in ANSI C, which does not allow declaring variables after statements. Let's stick to that convention to not introduce compilation issues and for consistency sake.

2023-02-18 20:37 UTC, closed without merging

2023-02-18 20:38 UTC, Zeex commented
Ended up implementing it a little differently in master.